
// postData() async {
//
//   // var response1 ;
//   http.Response response= await http.post(
//     Uri.parse("https://x-fit-backend-graduation-project.vercel.app/api/v1/user/register"),body:{
//     "name":_emailController.text,
//     "email" : _emailController.text.trim(),
//     "password": _phoneController.text,
//     "gender": _h.text,
//     "age":_ageController.text,
//     "weight":_weightController.text,
//     "height": _heightController.text,
//     "goal" :  _w.text,
//     "experience" :_b.text,
//     "bodyFatPercentage" : _bodyFatPercentageController.text,
//     "muscleMass" : _muscleMassController.text,
//     "preferredExerciseTypes": _u.text,
//     "workoutFrequencyPreference":_v.text,
//     "workoutDurationPreference":_x.text,
//     "trainingEnvironmentPreference":_t.text  ,
//     "accessToEquipment":_s.text,
//     "motivationLevel" :_m.text ,
//     "stressLevels":  _stressLevelsController.text,
//   },
//
//   );
//   String  autogenerated=jsonEncode(response.body);
//   //    data = jsonEncode(response) as Map ;
//   if (response.statusCode == 200) {
//     final json=jsonDecode(response.body);
//
//     // Registration successful
//     print('Registration successful');
//   } else {
//     // Registration failed
//     print('Registration failed');
//   }
//
//   return response.body;}
