import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:http/http.dart';
import 'package:http/http.dart' as http;
import 'package:xfit/screens/PrimaryButton.dart';
import 'package:xfit/screens/Validator/Sign3.dart';
import 'package:xfit/screens/checkbox.dart';
import 'package:xfit/screens/logIn_option.dart';
import 'package:xfit/screens/login.dart';
import 'package:xfit/screens/sign2.dart';
import 'package:xfit/screens/signup_form.dart';
import 'package:xfit/screens/theme.dart';


class SignUpScreen extends StatefulWidget{

  @override
  State<SignUpScreen> createState() => _SignUpScreenState();
}

class _SignUpScreenState extends State<SignUpScreen> {
  TextEditingController name=TextEditingController();
  TextEditingController email=TextEditingController();
  TextEditingController phone=TextEditingController();
  TextEditingController password=TextEditingController();
  @override
  Widget build(BuildContext context) {
    return Scaffold(
    body: SingleChildScrollView(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          SizedBox(height: 45,),
          Padding(
            padding: kDefaultPadding,
            child: Text(
              "Create Account",
              style:titleText ,
            ),
          ),
          SizedBox(height: 5,),
          Padding(
            padding: kDefaultPadding,
            child: Row(
              children: [
                Text(
                  "Already A member?",
                  style: subTitle,
                ),
                SizedBox(width: 5),
                GestureDetector(
                  onTap: (){
                    Navigator.push(
                        context,
                        MaterialPageRoute(
                          builder: (context)=>LoginScreen(),
                        )
                    );
                  },
                  child: Text(
                    "Log In",
                    style: textButton.copyWith(
                    decoration: TextDecoration.underline,
                      decorationThickness: 1
                  ),),
                )

              ],
            ),
          ),
          SizedBox(height: 10,),
          Padding(
            padding: kDefaultPadding,
            child: SignUpForm(),
          ),
          SizedBox(height: 20,),
          Padding(
            padding:kDefaultPadding,
            child: CheckBox(
              "Agree to terms and conditions"
            ),
          ),
          // SizedBox(height: 20,),
          // Padding(
          //   padding:kDefaultPadding,
          //   child: CheckBox(
          //       "I Have at least 18 years old"
          //   ),
          // ),

          SizedBox(height: 12,),
          Padding(
            padding: kDefaultPadding,
            child: GestureDetector(
               onTap: (){
                 try {
                   regestratioUser();
                 }catch(e){
                   print(e);
                 }
                Navigator.push(
                    context,
                    MaterialPageRoute(
                      builder: (context)=>Sign2())
                );
              },
                child: PrimaryButton(
                    buttonText: "Continue Sign Up")
            ),
          ),
          SizedBox(height: 20,),
          Padding(
            padding: kDefaultPadding,
         //   child: GestureDetector(
            //  onTap: (){
              //   Navigator.push(
              //       context,
              //       MaterialPageRoute(
              //         builder: (context)=>SignUpScreen(),
              //       )
              //   );
              // },
              child: Text(
                  "Or log in with",
                style: subTitle.copyWith(
                  color: kBlackColor
                ),
              ),
           // ),
          ),
         SizedBox(height: 20,),
         Padding(
           padding: kDefaultPadding,
           child: LogInOption(),
         ),
          SizedBox(height: 20,),

        ],
      ),
    ),
    );
  }

  Future regestratioUser() async{
    Map mapdata={
      "name": name.text,
      "email" : email.text.trim(),
      "phone" :phone.text,
      "password":password.text

    };

    final response= await http.post(
        Uri.parse("https://x-fit-backend-graduation-project.vercel.app/api/v1/user/register"),body:
     mapdata
    );
print(response);
    var data=Autogenerated.fromJson(jsonDecode(response.body));


  }
}